### ISSUE TITLE
Set license expression

### ISSUE THREAD

**Issue by thompson-tomo** [cinderblocks/zlib.net#4]
### Summary
I wish for the nuget packages to have the licence expression property set correctly k

### Details

The licence expression property should be set to the correct licence type (depending on the repo) as this will enable analysis of licences in use to occur in external tools & the license type will be shown in Nuget etc.

**Comment by thompson-tomo** [comment]
Note this is just needing a new version bump + release as the master has not been released.

**Comment by cinderblocks** [comment]
What do you mean? It is specified in csproj:
```
<PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
```

**Comment by thompson-tomo** [comment]
That is correct but there has been no release of the package since that change has been made hence nuget.org is still using the file.

**Comment by cinderblocks** [comment]
Aha, I see. New package should be released in the next two weeks once I had another code signing certificate.
